# Pandas 

Useful for Data Processing and Analysis 

## Pandas Data Frame:

Pandas DataFrame is two-dimensional tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd
import numpy as np

In [10]:
# from sklearn.datasets import load_boston

# boston_dataset = load_boston()

# type(boston_dataset)

# print(boston_dataset)


# ImportError                               Traceback (most recent call last)
# Cell In[9], line 1
# ----> 1 from sklearn.datasets import load_boston
#       3 boston_dataset = load_boston()
#       5 type(boston_dataset)

# File c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\datasets\__init__.py:161, in __getattr__(name)
#     110 if name == "load_boston":
#     111     msg = textwrap.dedent(
#     112         """
#     113         `load_boston` has been removed from scikit-learn since version 1.2.
#    (...)    159         """
#     160     )
# --> 161     raise ImportError(msg)
#     162 try:
#     163     return globals()[name]

# ImportError: 
# `load_boston` has been removed from scikit-learn since version 1.2.

# The Boston housing prices dataset has an ethical problem: as
# investigated in [1], the authors of this dataset engineered a
# non-invertible variable "B" assuming that racial self-segregation had a
# positive impact on house prices [2]. Furthermore the goal of the
# ...
# [2] Harrison Jr, David, and Daniel L. Rubinfeld.
# "Hedonic housing prices and the demand for clean air."
# Journal of environmental economics and management 5.1 (1978): 81-102.
# <https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>
# Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

In [27]:
from sklearn.datasets import fetch_california_housing

california = fetch_california_housing()
print(california.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [4]:
california_df = pd.DataFrame(california.data,columns=california.feature_names)
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [5]:
california_df.shape

(20640, 8)

In [6]:
df = pd.read_csv('housing.csv')
print(df.head())

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [7]:
df.tail()

        RM  LSTAT  PTRATIO      MEDV
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

In [8]:
# Shape 

s=df.shape
print(s)
type(california_df)

(489, 4)

pandas.core.frame.DataFrame

In [ ]:
# Loading data from excel file

# pd.read_excel('file path')

In [9]:
# Exporting a DataFrame to a csv file

california_df.to_csv('california.csv')

In [ ]:
# Exporting pandas dataframe to an excel file

# california_df.to_excel('filname')

In [10]:
# Create dataframe with random values 

random_df = pd.DataFrame(np.random.rand(20,10)) # values will be 0-1

random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.167485,0.710408,0.348646,0.162947,0.111748,0.100794,0.841210,0.249969,0.660387,0.465555
1,0.721195,0.767452,0.724467,0.813437,0.174761,0.971915,0.073794,0.263077,0.403596,0.209597
2,0.416271,0.701698,0.091595,0.576067,0.513991,0.068675,0.780186,0.304456,0.345257,0.482361
3,0.527705,0.848905,0.463162,0.427456,0.681060,0.942143,0.534229,0.237818,0.339709,0.149301
4,0.534102,0.321316,0.106132,0.169713,0.930242,0.903213,0.625760,0.259989,0.975375,0.573797

In [11]:
random_df.shape

(20, 10)

In [12]:
# Inspecting a DataFrame

# Finding the no. of rows and columns 

california_df.shape

(20640, 8)

In [13]:
# first 5 rows 

california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [33]:
# last 5 rows of the DataFrames

california_df.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   RM       489 non-null    float64
 1   LSTAT    489 non-null    float64
 2   PTRATIO  489 non-null    float64
 3   MEDV     489 non-null    float64
dtypes: float64(4)
memory usage: 15.4 KB

In [36]:
# informations about dataframe

california_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [15]:
# finding the no. of missing values

california_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [16]:
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [19]:
# Counting the values based on the labels

california_df.value_counts('Longitude')
california_df.value_counts('AveRooms')

AveRooms
5.000000      27
4.500000      22
4.000000      21
6.000000      20
5.333333      13
              ..
4.736964       1
4.736413       1
4.736364       1
4.736334       1
141.909091     1
Name: count, Length: 19392, dtype: int64

In [ ]:
# group the values based on their mean

california_df.groupby('Longitude').mean()  

# eg - on diabetes data set value 0 means is not diabetes all parameter's mean value is shown similar for 1 - diabetes

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude
Longitude,,,,,,,
-124.35,3.0147,52.0,6.740741,1.111111,806.0,2.985185,40.54
-124.30,2.5055,18.0,5.730286,1.159643,1271.0,2.721776,41.82
-124.27,2.5179,36.0,5.051613,1.135484,1194.0,2.567742,40.69
-124.26,2.3571,52.0,6.008130,1.067751,907.0,2.457995,40.58
-124.25,1.9417,32.0,7.647059,2.240642,434.0,2.320856,40.28
...,...,...,...,...,...,...,...
-114.56,1.6509,17.0,6.153846,1.487179,333.0,2.846154,33.69
-114.55,1.2750,19.0,4.226974,1.348684,1431.0,2.353618,32.80
-114.49,1.6154,17.0,62.422222,14.111111,83.0,1.844444,33.97
-114.47,1.8200,19.0,16.522678,4.105832,1129.0,2.438445,34.40
-114.31,1.4936,15.0,11.889831,2.718220,1015.0,2.150424,34.19

In [21]:
# count or number of values 

california_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [22]:
# mean value column wise

california_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [23]:
california_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [24]:
california_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [25]:
california_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [26]:
# All statistical measures in one go

california_df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [39]:
california_df['Price'] = california.target

In [40]:
california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [41]:
# Removing a particular row

california_df.drop(index=0,axis=0)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [44]:
# Drop a column

california_df.drop(columns='HouseAge',axis=1)

,MedInc,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...
20635,1.5603,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [45]:
# Locating row using index value

california_df.iloc[2]

MedInc          7.257400
HouseAge       52.000000
AveRooms        8.288136
AveBedrms       1.073446
Population    496.000000
AveOccup        2.802260
Latitude       37.850000
Longitude    -122.240000
Price           3.521000
Name: 2, dtype: float64

In [47]:
# locating a particular column

print(california_df.iloc[:,0])  # first column 
print(california_df.iloc[:,1])  # second column 
print(california_df.iloc[:,-1]) # last column

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20640, dtype: float64
0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ...
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

In [49]:
# Correlation 

# Positive correlation and negative corelarion

california_df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
Price,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000